import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Header from "@/components/header/Header";
import dynamic from "next/dynamic";
import Hvordan from "@/components/sections/Hvordan";
import Blog from "@/components/sections/Blog";
import { FAQ } from "@/components/sections/FAQ";
import Footer from "@/components/sections/Footer";
import localFont from "next/font/local";

const satoshi = localFont({
  variable: "--font-sans",
  src: [
    {
      path: "./fonts/Satoshi-Bold.woff2",
    },
    {
      path: "./fonts/Satoshi-Light.woff2",
    },
    {
      path: "./fonts/Satoshi-Medium.woff2",
    },
    {
      path: "./fonts/Satoshi-Regular.woff2",
    },
    {
      path: "./fonts/Satoshi-Variable.woff2",
      style: "variable",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SmoothScroll = dynamic(() => import("contexts/SmoothScroll.context"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          satoshi.variable
        )}
      >
        <SmoothScroll />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
